
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author j0nhc
 */
public class Calculadora01 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculadora01.class.getName());

    /**
     * Creates new form Calculadora01
     */
    public Calculadora01() {
        initComponents();
    }
    String op = "";
    double valor0 = 0;
    double valor1 = 0+valor0;
    double valor2 = 0;
    double resultado = 0;

    private void operadores(String operacao) {

        valor1   = Double.parseDouble(txfExibir.getText());
        txfExibir.setText(" ");
        op = operacao;
    }

    private void digita(String caracter) {
        if (txfExibir.getText().equals("0,0")) { // Subistituindo o inicial pela nova entrada 
            txfExibir.setText(caracter);
        } else {
            if (txfExibir.getText().contains(",") && caracter.contains(",")) {
                //vazio para ignorar a entrada de pontos consecutivos 
            } else {
                txfExibir.setText(txfExibir.getText().concat(caracter));
                //primeiro pegar o numeral apertado e CONCATENAR com o texto já exibido.
                //depois vai SETAR (setAction)na nova exibiçao 
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jb0 = new javax.swing.JButton();
        jbSoma = new javax.swing.JButton();
        jbSubtrair = new javax.swing.JButton();
        jbMultiplicar = new javax.swing.JButton();
        jbDividir = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbIgual = new javax.swing.JButton();
        jbVirgula = new javax.swing.JButton();
        txfExibir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("CALCULADORA");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jb1.setBackground(new java.awt.Color(102, 102, 102));
        jb1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb1.setText("1");
        jb1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jb1.setPreferredSize(new java.awt.Dimension(50, 50));
        jb1.addActionListener(this::jb1ActionPerformed);

        jb2.setBackground(new java.awt.Color(102, 102, 102));
        jb2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb2.setText("2");
        jb2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jb2.setPreferredSize(new java.awt.Dimension(50, 50));
        jb2.addActionListener(this::jb2ActionPerformed);

        jb3.setBackground(new java.awt.Color(102, 102, 102));
        jb3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb3.setText("3");
        jb3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jb3.setPreferredSize(new java.awt.Dimension(50, 50));
        jb3.addActionListener(this::jb3ActionPerformed);

        jb4.setBackground(new java.awt.Color(102, 102, 102));
        jb4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb4.setText("4");
        jb4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jb4.setPreferredSize(new java.awt.Dimension(50, 50));
        jb4.addActionListener(this::jb4ActionPerformed);

        jb5.setBackground(new java.awt.Color(102, 102, 102));
        jb5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb5.setText("5");
        jb5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jb5.setPreferredSize(new java.awt.Dimension(50, 50));
        jb5.addActionListener(this::jb5ActionPerformed);

        jb6.setBackground(new java.awt.Color(102, 102, 102));
        jb6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb6.setText("6");
        jb6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jb6.setPreferredSize(new java.awt.Dimension(50, 50));
        jb6.addActionListener(this::jb6ActionPerformed);

        jb7.setBackground(new java.awt.Color(102, 102, 102));
        jb7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb7.setText("7");
        jb7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jb7.setPreferredSize(new java.awt.Dimension(50, 50));
        jb7.addActionListener(this::jb7ActionPerformed);

        jb8.setBackground(new java.awt.Color(102, 102, 102));
        jb8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb8.setText("8");
        jb8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jb8.setPreferredSize(new java.awt.Dimension(50, 50));
        jb8.addActionListener(this::jb8ActionPerformed);

        jb9.setBackground(new java.awt.Color(102, 102, 102));
        jb9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb9.setText("9");
        jb9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jb9.setPreferredSize(new java.awt.Dimension(50, 50));
        jb9.addActionListener(this::jb9ActionPerformed);

        jb0.setBackground(new java.awt.Color(102, 102, 102));
        jb0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb0.setText("0");
        jb0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jb0.setPreferredSize(new java.awt.Dimension(50, 50));
        jb0.addActionListener(this::jb0ActionPerformed);

        jbSoma.setBackground(new java.awt.Color(102, 102, 102));
        jbSoma.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbSoma.setText("+");
        jbSoma.setAlignmentY(0.0F);
        jbSoma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jbSoma.setPreferredSize(new java.awt.Dimension(50, 50));
        jbSoma.addActionListener(this::jbSomaActionPerformed);

        jbSubtrair.setBackground(new java.awt.Color(102, 102, 102));
        jbSubtrair.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbSubtrair.setText("-");
        jbSubtrair.setAlignmentY(0.0F);
        jbSubtrair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jbSubtrair.setPreferredSize(new java.awt.Dimension(50, 50));
        jbSubtrair.addActionListener(this::jbSubtrairActionPerformed);

        jbMultiplicar.setBackground(new java.awt.Color(102, 102, 102));
        jbMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbMultiplicar.setText("x");
        jbMultiplicar.setAlignmentY(0.0F);
        jbMultiplicar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jbMultiplicar.setPreferredSize(new java.awt.Dimension(50, 50));
        jbMultiplicar.addActionListener(this::jbMultiplicarActionPerformed);

        jbDividir.setBackground(new java.awt.Color(102, 102, 102));
        jbDividir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbDividir.setText("/");
        jbDividir.setAlignmentY(0.0F);
        jbDividir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jbDividir.setPreferredSize(new java.awt.Dimension(50, 50));
        jbDividir.addActionListener(this::jbDividirActionPerformed);

        jbLimpar.setBackground(new java.awt.Color(102, 102, 102));
        jbLimpar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbLimpar.setText("C");
        jbLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jbLimpar.setPreferredSize(new java.awt.Dimension(50, 50));
        jbLimpar.addActionListener(this::jbLimparActionPerformed);

        jbIgual.setBackground(new java.awt.Color(102, 102, 102));
        jbIgual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbIgual.setText("=");
        jbIgual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jbIgual.setPreferredSize(new java.awt.Dimension(50, 50));
        jbIgual.addActionListener(this::jbIgualActionPerformed);

        jbVirgula.setBackground(new java.awt.Color(102, 102, 102));
        jbVirgula.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbVirgula.setText(",");
        jbVirgula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jbVirgula.setPreferredSize(new java.awt.Dimension(50, 50));
        jbVirgula.addActionListener(this::jbVirgulaActionPerformed);

        txfExibir.setBackground(new java.awt.Color(255, 255, 255));
        txfExibir.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txfExibir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txfExibir.setText("0,0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jb0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbDividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbSubtrair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbSoma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(txfExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbDividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jbIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        digita("1");
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        digita("2");
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        digita("3");
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        digita("4");
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
        digita("5");
    }//GEN-LAST:event_jb5ActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        digita("6");
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        digita("7");
    }//GEN-LAST:event_jb7ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        digita("8");
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
        digita("9");
    }//GEN-LAST:event_jb9ActionPerformed

    private void jb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb0ActionPerformed
        digita("0");
    }//GEN-LAST:event_jb0ActionPerformed

    private void jbSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSomaActionPerformed
        operadores("+");
        //digita("+");
    }//GEN-LAST:event_jbSomaActionPerformed

    private void jbSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubtrairActionPerformed
        operadores("-");
        // digita("-");   
    }//GEN-LAST:event_jbSubtrairActionPerformed

    private void jbMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMultiplicarActionPerformed
        operadores("x");
        //digita("x");
    }//GEN-LAST:event_jbMultiplicarActionPerformed

    private void jbDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDividirActionPerformed
        operadores("/");
        //digita("/");
    }//GEN-LAST:event_jbDividirActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        txfExibir.setText("0,0");
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIgualActionPerformed

        valor2 = Double.parseDouble(txfExibir.getText());
        switch (op) {

            case "+":
                resultado = valor1 + valor2;

                break;
            case "-":
                resultado = valor1 - valor2;
                //subitrair 

                break;
            case "x":
                resultado = valor1 * valor2;
                //Multiplicar 

                break;
            case "/":
                resultado = valor1 / valor2;
                //Dividr 

                break;

            default:
                JOptionPane.showMessageDialog(null, "Erro na operação", "erroooouu", JOptionPane.WARNING_MESSAGE);
        }
        String resultadoStr = String.valueOf(resultado);
        txfExibir.setText(resultadoStr);
    }//GEN-LAST:event_jbIgualActionPerformed

    private void jbVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVirgulaActionPerformed
        digita(",");
    }//GEN-LAST:event_jbVirgulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculadora01().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb0;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbDividir;
    private javax.swing.JButton jbIgual;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbMultiplicar;
    private javax.swing.JButton jbSoma;
    private javax.swing.JButton jbSubtrair;
    private javax.swing.JButton jbVirgula;
    private javax.swing.JLabel txfExibir;
    // End of variables declaration//GEN-END:variables
}
