
import javax.swing.JOptionPane;
import java.awt.Image;
import javax.swing.ImageIcon;

public class CalculoG extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculoG.class.getName());

    public CalculoG() {
        initComponents();
        planetaIMG();
    }
    
    
    
 private void mostrarPlaneta(String caminhoImagem) {
        // Cria ícone da imagem
        ImageIcon icon = new ImageIcon(caminhoImagem);
        // Redimensiona imagem para tamanho fixo
        Image imagem = icon.getImage().getScaledInstance(
                120, // largura
                120, // altura
                Image.SCALE_SMOOTH
        );
        // Coloca imagem redimensionada no JLabel
        lblPlaneta.setIcon(new ImageIcon(imagem));
    }
    
    public void planetaIMG(){
        switch (cbPlanetas.getSelectedItem().toString()) {
            case "Mercúrio":
                mostrarPlaneta("src/img/mercurio_img.png");
                break;
            case "Vênus":
                mostrarPlaneta("src/img/venus_img.png");
                break;
            case "Terra":
                mostrarPlaneta("src/img/terra_img.png");
                break;
            case "Marte":
                mostrarPlaneta("src/img/marte_img.png");

                break;
            case "Júpiter":
                mostrarPlaneta("src/img/jupiter_img.png");
                
                break;
            case "Saturno":
                mostrarPlaneta("src/img/saturno_img.png");
                
                break;
            case "Urano":
                mostrarPlaneta("src/img/urano_img.png");
                
                break;
            case "Netuno":
                mostrarPlaneta("src/img/netuno_img.png");
                
                break;
            case "Selena :)":
                mostrarPlaneta("src/img/lua_img.png");
                break;
            default:
                JOptionPane.showMessageDialog(null,"Nada selecionado");
        }
        
    }
   
            
    public double planeta(){
        
        double gravitPlanet =0;
        
        switch (cbPlanetas.getSelectedItem().toString()) {
            case "Mercúrio":
                gravitPlanet = 3.6;
                                
                break;
            case "Vênus":
                gravitPlanet = 8.7;
                
                break;
            case "Terra":
                gravitPlanet = 9.81;
               
                break;
            case "Marte":
                gravitPlanet = 3.7;
                
                break;
            case "Júpiter":
                gravitPlanet = 24.79;
                
                break;
            case "Saturno":
                gravitPlanet = 10.44;
                
                break;
            case "Urano":
                gravitPlanet = 8.69;
                
                break;
            case "Netuno":
                gravitPlanet = 11.15;
                
                break;
            case "Selena :)":
                gravitPlanet = 1.6;
                
                break;
            default:
                JOptionPane.showMessageDialog(null,"Nada selecionado");
        }
        return gravitPlanet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfPeso1 = new javax.swing.JTextField();
        cbPlanetas = new javax.swing.JComboBox<>();
        jbCalculopeso = new javax.swing.JButton();
        lblPlaneta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CalculoGravidade");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Peso na terra em Kg :");

        txfPeso1.addActionListener(this::txfPeso1ActionPerformed);

        cbPlanetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mercúrio", "Vênus", "Terra", "Marte", "Júpiter", "Saturno", "Urano", "Netuno", "Selena :)" }));
        cbPlanetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbPlanetasMouseClicked(evt);
            }
        });
        cbPlanetas.addActionListener(this::cbPlanetasActionPerformed);

        jbCalculopeso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCalculopeso.setText("Calcular peso ");
        jbCalculopeso.addActionListener(this::jbCalculopesoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbCalculopeso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(txfPeso1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(cbPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(lblPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txfPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbCalculopeso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
      

    private void cbPlanetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanetasActionPerformed
      planetaIMG();
    }//GEN-LAST:event_cbPlanetasActionPerformed

    private void jbCalculopesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalculopesoActionPerformed
        double pesoTerra =Double.parseDouble(txfPeso1.getText());
        double resultadoG = (pesoTerra/10) * planeta();
        planetaIMG();
        JOptionPane.showMessageDialog(null, "Seu peso em "+cbPlanetas.getSelectedItem().toString()+" é de :"+resultadoG+" kg");
    }//GEN-LAST:event_jbCalculopesoActionPerformed

    private void txfPeso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPeso1ActionPerformed
    }//GEN-LAST:event_txfPeso1ActionPerformed

    private void cbPlanetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPlanetasMouseClicked
        planetaIMG();
    }//GEN-LAST:event_cbPlanetasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculoG().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbPlanetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCalculopeso;
    private javax.swing.JLabel lblPlaneta;
    private javax.swing.JTextField txfPeso1;
    // End of variables declaration//GEN-END:variables
}
