/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 1091771
 */
public class MenuInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuInicial.class.getName());

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbCalculadora = new javax.swing.JButton();
        jbTriangulo = new javax.swing.JButton();
        jbtCaixadeselecao = new javax.swing.JButton();
        jbtBlackhole = new javax.swing.JButton();
        jbtConfig = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();
        jbJOKEMPO = new javax.swing.JButton();
        jbtFoto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jbMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jbMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        miCadastrar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        miBuscarIMG = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu_inicial");

        jbCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calculadoraimg.png"))); // NOI18N
        jbCalculadora.addActionListener(this::jbCalculadoraActionPerformed);

        jbTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trianguloimg.png"))); // NOI18N
        jbTriangulo.addActionListener(this::jbTrianguloActionPerformed);

        jbtCaixadeselecao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-box.gif"))); // NOI18N
        jbtCaixadeselecao.addActionListener(this::jbtCaixadeselecaoActionPerformed);

        jbtBlackhole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-black-hole-100.png"))); // NOI18N
        jbtBlackhole.addActionListener(this::jbtBlackholeActionPerformed);

        jbtConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/engrenagem_gif.gif"))); // NOI18N
        jbtConfig.addActionListener(this::jbtConfigActionPerformed);

        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_img.png"))); // NOI18N
        jbCadastrar.addActionListener(this::jbCadastrarActionPerformed);

        jbJOKEMPO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedra_img.png"))); // NOI18N
        jbJOKEMPO.addActionListener(this::jbJOKEMPOActionPerformed);

        jbtFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fotos_img.png"))); // NOI18N
        jbtFoto.addActionListener(this::jbtFotoActionPerformed);

        jMenu1.setText("Formularios");

        jMenuItem1.setText("Calculadora");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Triângulos");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jbMenuItem3.setSelected(true);
        jbMenuItem3.setText("Box");
        jbMenuItem3.addActionListener(this::jbMenuItem3ActionPerformed);
        jMenu1.add(jbMenuItem3);

        jbMenuItem4.setSelected(true);
        jbMenuItem4.setText("Calculo Gravidade");
        jbMenuItem4.addActionListener(this::jbMenuItem4ActionPerformed);
        jMenu1.add(jbMenuItem4);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Configurações de jogo");
        jCheckBoxMenuItem1.addActionListener(this::jCheckBoxMenuItem1ActionPerformed);
        jMenu1.add(jCheckBoxMenuItem1);

        miCadastrar.setText("Cadastrar");
        miCadastrar.addActionListener(this::miCadastrarActionPerformed);
        jMenu1.add(miCadastrar);

        jMenuItem3.setText("JOKENPO");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        miBuscarIMG.setText("Buscar Imagem");
        miBuscarIMG.addActionListener(this::miBuscarIMGActionPerformed);
        jMenu1.add(miBuscarIMG);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sair");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCaixadeselecao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbJOKEMPO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtBlackhole, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtCaixadeselecao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jbTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jbCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE))
                    .addComponent(jbtBlackhole, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbJOKEMPO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       Calculadora01 c = new Calculadora01();
       c.setVisible(true);
      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       QualTriangulo triangulo = new QualTriangulo();
       triangulo.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalculadoraActionPerformed
        Calculadora01 c = new Calculadora01();
       c.setVisible(true);
    }//GEN-LAST:event_jbCalculadoraActionPerformed

    private void jbTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTrianguloActionPerformed
        QualTriangulo triangulo = new QualTriangulo();
        triangulo.setVisible(true);
    }//GEN-LAST:event_jbTrianguloActionPerformed

    private void jbtCaixadeselecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCaixadeselecaoActionPerformed
        ExComboBox combox = new ExComboBox();
        combox.setVisible(true);
    }//GEN-LAST:event_jbtCaixadeselecaoActionPerformed

    private void jbtBlackholeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBlackholeActionPerformed
        CalculoG cg =new CalculoG();
        cg.setVisible(true);
        
    }//GEN-LAST:event_jbtBlackholeActionPerformed

    private void jbtConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfigActionPerformed
        ConfiguracoesJogo config = new ConfiguracoesJogo();
        config.setVisible(true);
    }//GEN-LAST:event_jbtConfigActionPerformed

    private void jbMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuItem3ActionPerformed
        ExComboBox combox = new ExComboBox();
        combox.setVisible(true);
    }//GEN-LAST:event_jbMenuItem3ActionPerformed

    private void jbMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuItem4ActionPerformed
        CalculoG cg =new CalculoG();
        cg.setVisible(true);
    }//GEN-LAST:event_jbMenuItem4ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        ConfiguracoesJogo config = new ConfiguracoesJogo();
        config.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
       Cadastro c = new Cadastro();
       c.setVisible(true);
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void miCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarActionPerformed
        Cadastro c = new Cadastro();
        c.setVisible(true);
    }//GEN-LAST:event_miCadastrarActionPerformed

    private void jbJOKEMPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJOKEMPOActionPerformed
        Jokenpo j = new Jokenpo();
        j.setVisible(true);
    }//GEN-LAST:event_jbJOKEMPOActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         Jokenpo j = new Jokenpo();
         j.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jbtFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFotoActionPerformed
       Buscando b = new Buscando();
       b.setVisible(true);
    }//GEN-LAST:event_jbtFotoActionPerformed

    private void miBuscarIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscarIMGActionPerformed
       Buscando b = new Buscando();
       b.setVisible(true);
    }//GEN-LAST:event_miBuscarIMGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCalculadora;
    private javax.swing.JButton jbJOKEMPO;
    private javax.swing.JCheckBoxMenuItem jbMenuItem3;
    private javax.swing.JCheckBoxMenuItem jbMenuItem4;
    private javax.swing.JButton jbTriangulo;
    private javax.swing.JButton jbtBlackhole;
    private javax.swing.JButton jbtCaixadeselecao;
    private javax.swing.JButton jbtConfig;
    private javax.swing.JButton jbtFoto;
    private javax.swing.JMenuItem miBuscarIMG;
    private javax.swing.JMenuItem miCadastrar;
    // End of variables declaration//GEN-END:variables
}
